# Generated by Django 5.0.4 on 2024-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('va', 'Вакансия'), ('or', 'Заказ')], max_length=2, verbose_name='Категория'),
        ),
    ]
